"""widen quiz_questions correct_answer to unbounded text

Revision ID: 089b9a2d134f
Revises: 0cd36119763b
Create Date: 2026-08-25 06:38:29.248374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089b9a2d134f'
down_revision: Union[str, Sequence[str], None] = '0cd36119763b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_questions', 'correct_answer',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_questions', 'correct_answer',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
