"""widen quiz_questions correct_answer to unbounded text

Revision ID: 089b9a2d134f
Revises: 0cd36119763b
Create Date: 2026-08-25 06:38:29.248374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '089b9a2d134f'
down_revision: Union[str, Sequence[str], None] = '0cd36119763b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_questions', 'correct_answer',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.Text(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema.

    이 upgrade()가 correct_answer를 무제한 Text로 넓힌 건(quiz_question.py
    모델 자신의 주석 참고) AI가 생성하는 값이라 길이 제한이 없어서다. 이
    downgrade()는 그 이유를 무시하고 그냥 VARCHAR(500)으로 되돌리려 하는데,
    500자를 넘는 correct_answer가 하나라도 있으면(184라운드 기준 실제로
    가능한 값이라 되돌린 이유이기도 함) `ALTER TABLE ... TYPE VARCHAR(500)`
    이 그 자리에서 `StringDataRightTruncationError`로 실패한다. 로컬
    Postgres 16에 600자짜리 correct_answer를 가진 문항 하나만 넣고 직접
    재현해 확인했다 - 아무 안내 없이 로우레벨 asyncpg 스택트레이스만 남기고
    죽는다.

    e220f5de306a의 downgrade()(같은 라운드가 고침)와 같은 이유로, 자동으로
    잘라내거나 지우는 대신 원인이 자명한 명시적 에러로 먼저 막는다.
    """
    bind = op.get_bind()
    has_long_answer = bind.execute(
        sa.text("SELECT 1 FROM quiz_questions WHERE length(correct_answer) > 500 LIMIT 1")
    ).first()
    if has_long_answer is not None:
        raise RuntimeError(
            "089b9a2d134f downgrade가 막혔습니다: 500자를 넘는 correct_answer를 "
            "가진 quiz_questions 행이 존재합니다. 이 리비전으로 되돌리면 "
            "VARCHAR(500)으로 자르다가 실패합니다. 해당 문항을 수동으로 정리한 "
            "뒤 다시 시도하세요(자동으로 자르지 않는 이유: 데이터 손실이라 "
            "운영자의 명시적 판단이 필요합니다)."
        )
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_questions', 'correct_answer',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    # ### end Alembic commands ###
