"""add source_text to quizzes for rag backfill recovery

Revision ID: 0cd36119763b
Revises: f1c5ccb154c6
Create Date: 2026-08-24 08:38:51.643647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cd36119763b'
down_revision: Union[str, Sequence[str], None] = 'f1c5ccb154c6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quizzes', sa.Column('source_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quizzes', 'source_text')
    # ### end Alembic commands ###
