"""add composite index on knowledge_chunks user_id embedding_model created_at

Revision ID: f8c776ddf837
Revises: 089b9a2d134f
Create Date: 2026-08-25 22:34:21.665912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c776ddf837'
down_revision: Union[str, Sequence[str], None] = '089b9a2d134f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_knowledge_chunks_user_id_embedding_model_created_at', 'knowledge_chunks', ['user_id', 'embedding_model', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_knowledge_chunks_user_id_embedding_model_created_at', table_name='knowledge_chunks')
    # ### end Alembic commands ###
